;METADATA=(Diff=true, UseCommands=true)

[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
+GameplayTagTableList=None
+GameplayTagRedirects=(OldTagName="Damage.Explosion",NewTagName="GameData.Damage.Explosion")
+GameplayTagRedirects=(OldTagName="Damage.Magic.Air",NewTagName="GameData.Damage.Magic.Air")
+GameplayTagRedirects=(OldTagName="Damage.Magic.Earth",NewTagName="GameData.Damage.Magic.Earth")
+GameplayTagRedirects=(OldTagName="Damage.Magic.Fire",NewTagName="GameData.Damage.Magic.Fire")
+GameplayTagRedirects=(OldTagName="Damage.Magic.Water",NewTagName="GameData.Damage.Magic.Water")
+GameplayTagRedirects=(OldTagName="Damage.Projectile",NewTagName="GameData.Damage.Projectile")
+GameplayTagRedirects=(OldTagName="Damage.Slicing",NewTagName="GameData.Damage.Slicing")
+GameplayTagRedirects=(OldTagName="GameData.Attribute.PoisonResistence",NewTagName="GameData.Attribute.PoisonResistance")
+GameplayTagRedirects=(OldTagName="GameData.Attribute.SlicingResistance",NewTagName="GameData.Attribute.SliceResistance")
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GameData",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.AirResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.Defence",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.EarthResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.ElectricResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.ExplosionResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.FireResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.Health",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.MaxHealth",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.PoisonResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.ProjectileResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.SliceResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Attribute.WaterResistance",DevComment="")
+GameplayTagList=(Tag="GameData.Damage",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Explosion",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Magic.Air",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Magic.Earth",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Magic.Electric",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Magic.Fire",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Magic.Water",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Poison",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Projectile",DevComment="")
+GameplayTagList=(Tag="GameData.Damage.Slicing",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.AttributeInitialisation",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Combat.CharacterStatus.Invisible",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Combat.Damage",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Combat.Defend",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Combat.Healing",DevComment="")
+GameplayTagList=(Tag="GameplayEffect.Combat.ManaUsage",DevComment="")
+GameplayTagList=(Tag="SpecialCardEffect.OneMoreDraw",DevComment="")
+GameplayTagList=(Tag="SpecialCardEffect.Reshuffle",DevComment="")
+GameplayTagList=(Tag="SpecialCardEffect.TakeFromDiscardedPile",DevComment="")

